[2023] Add `rules.php`
ia-toki/osn pull request #10
Opened 2023-08-11 04:43 UTC by Si-plus-plus

Poin A - F mengacu pada aturan 2022
Poin G mengacu pada aturan 2019 (onsite)

Spesifikasi teknis dan spesifikasi grader masih tbd

2023-08-14 13:30 UTC, fushar requested changes

2023-08-14 13:30 UTC, fushar commented on app/Views/OSN2023/rules.php
> +    <li><s>g++ 9.4 (C++11 / C++17 / C++20)</s> -- tbd</li>
```
$ g++ --version
g++ (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
```

2023-08-14 13:30 UTC, fushar commented on app/Views/OSN2023/rules.php
> +      <li>MinGW (C++xx) -- tbd</li>
Tulis MinGW aja dulu kayaknya gpp

2023-08-14 13:30 UTC, fushar commented on app/Views/OSN2023/rules.php
> +      <li>Laptop Acer AMD A8</li>
Ini mestinya PC deh.

Tapi karena belum pasti, hapus aja section ini

2023-08-14 13:30 UTC, fushar commented on app/Views/OSN2023/rules.php
> +<div class="bp3-callout bp3-intent-warning">
Notice ini hapus aja dulu karena tidak ada perbedaan sama sekali.

2023-08-14 13:30 UTC, fushar commented on app/Views/OSN2023/rules.php
> +      <li>gdb 8.1</li>
Versinya yakin? Kalau nggak, hapus aja dulu versinya.

2023-08-15 04:06 UTC, Si-plus-plus commented on app/Views/OSN2023/rules.php
> +      <li>MinGW (C++xx) -- tbd</li>
aku tulisnya MinGW (C++) aja ya, krn MinGW ada bahasa lain selain C++

2023-08-15 12:38 UTC, fushar approved these changes

2023-08-15 12:38 UTC, merged